### ISSUE TITLE
Vaffle ex command opens NerdTree

### ISSUE THREAD

**Issue by timsn** [cocopon/vaffle.vim#5]
It seems that vaffle interferes with NerdTree. I installed both plugins using vim-plug and tried to open vaffle with ex command `:Vaffle` and instead NerdTree opens full screen (like vaffle normally does).

If I deactivate the NerdTree plugin vaffle works like expected.

**Comment by cocopon** [comment]
I didn't expect using both Vaffle and NERDTree... If you really want to use them at the same time, would you tell me the situation?

Vaffle detects opening a directory and replace the buffer. Maybe NERDTree interferes this feature.

**Comment by markwu** [comment]
Sometimes, I need to use nerdtree to traverse my project structure, the project drawer style is more clear for this purpose. That's why I keep nerdtree there.

Of course I can use netrw for this porpose, but I prefer nerdtree, and less bugs.

BTW, I like vaffle, it fills the gap of filebeagle and dirvish, and also more lightweighted than vimfiler.  Well done.

**Comment by markwu** [comment]
Okay, I found a solution for this, just add the following config to your vimrc

``` vim
let NERDTreeHijackNetrw = 0
```

Then, everything goes back to normal.

**Comment by markwu** [comment]
Maybe you can consider add this as a FAQ to help file.
