### ISSUE TITLE
Open a file in a split

### ISSUE THREAD

**Issue by cocopon** [cocopon/vaffle.vim#9]
> Being able to open a file in a split and not replace the Vaffle window?
> https://github.com/cocopon/vaffle.vim/issues/6#issuecomment-325010237

**Comment by cookiengineer** [comment]
FWIW I kind of tried implementing the sidebar management on my own while managing the "buffer nr" of Vaffle in the same method.

The source is here: https://github.com/cookiengineer/.vim/blob/master/mappings.vim#L52
I bound it to the F1 key, because I'm never using the terminal help anyways :D

The only missing part for making it work with this is being able to set something like the "target buffer nr" for Vaffle; so that the open action will lead to the buffer being opened in the given buf nr. and not being opened in its own buffer as it is doing currently.

**Comment by cocopon** [comment]
Implemented in #17.
